# Generated by Django 2.1.5 on 2019-01-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time when object was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last time of object update.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time when object was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last time of object update.')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=1000)),
                ('like_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
