# Generated by Django 2.1.5 on 2019-01-26 01:21
from django.contrib.auth.hashers import make_password
from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model('users', 'NetworkUser')
    u = User(username="admin", email='networkadmin@email.com', is_active=True, is_superuser=True, is_staff=True)
    u.password = make_password('admin2019')
    u.save()


def reverse_func(apps, schema_editor):
    User = apps.get_model('users', 'NetworkUser')
    User.objects.filter(username="admin").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
