# Generated by Django 2.1.5 on 2019-01-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190126_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkuser',
            name='bio',
            field=models.TextField(blank=True, help_text="User's bio.", max_length=1000),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='city',
            field=models.CharField(blank=True, help_text="User's city.", max_length=100),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='github',
            field=models.CharField(blank=True, help_text="User's github account name.", max_length=100),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='state',
            field=models.CharField(blank=True, help_text="User's state.", max_length=100),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='website',
            field=models.CharField(blank=True, help_text="User's website url.", max_length=300),
        ),
    ]
