# Generated by Django 2.1.5 on 2019-01-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190127_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkuser',
            name='bio',
            field=models.TextField(blank=True, help_text="User's bio.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='networkuser',
            name='city',
            field=models.CharField(blank=True, help_text="User's city.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkuser',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of network user.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='networkuser',
            name='github',
            field=models.CharField(blank=True, help_text="User's github account name.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkuser',
            name='state',
            field=models.CharField(blank=True, help_text="User's state.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkuser',
            name='website',
            field=models.CharField(blank=True, help_text="User's website url.", max_length=300, null=True),
        ),
    ]
